### PR TITLE
feat: Adopt MPL-2.0 license

### PR DESCRIPTION
**Pull request by eliassjogreen**

### CODE REVIEW

**Review by lucsoft — APPROVED** [review]
LGTM

**Review by aapoalas — APPROVED** [review]
Could go with MIT for the website but anything's fine by me.

**Comment by eliassjogreen** [comment]
> Could go with MIT for the website but anything's fine by me.

@aapoalas I chose MPL just to match the main projects, but I agree MIT is also fine with me.

**Review by load1n9 — APPROVED** [review]
LGTM

**Pull request merged**
